name: update-site
on: [push]
jobs:
  update-git-repo:
    runs-on: [self-hosted]
    steps:
      # To make it working
      # 1. Need create git remote 'deploy' and update it
      #   git remote add deploy git@github.com:unidevel/mysite.git && git fetch deploy
      # 2. Create .env under actions folder, add TOKEN with your github access token
      # 3. Under the actions folder, run `docker compose up -d` to start the self-hosted runner
      - run: (cd /app; git rebase deploy/${{ github.ref_name }})

